#!/bin/bash
# scripts/run_alignment_qc.sh
#
# Purpose:
#   Performs post-alignment quality control on BAM files generated by HISAT2.
#   Generates summary statistics to evaluate mapping quality, alignment efficiency,
#   and sequencing depth across all samples.
#
# Outputs:
#   - qc/alignment_stats/*_flagstat.txt  - overall alignment summary (mapped/unmapped reads, duplicates, etc.)
#   - qc/alignment_stats/*_idxstats.txt  - per-chromosome mapping distribution
#
# Key metrics produced:
#   - Total reads per sample
#   - Mapped vs unmapped reads
#   - Mapping rate (%)
#   - Chromosome-level read distribution
#
# Dependencies:
#   - samtools
#
# Notes:
#   - Requires sorted and indexed BAM files (.bam + .bai recommended)
#   - Intended for post-alignment QC prior to quantification (featureCounts)

mkdir -p qc/alignment_stats

for bam in alignments/*.bam
do
    sample=$(basename $bam .bam)

    samtools flagstat $bam > qc/alignment_stats/${sample}_flagstat.txt
    samtools idxstats $bam > qc/alignment_stats/${sample}_idxstats.txt
done